SUSE readme added
sigstore/friends pull request #29
Opened 2022-03-10 15:36 UTC by msmeissn

#### Summary

#### Ticket Link

Fixes

#### Release Note

```release-note

```

2022-03-10 15:41 UTC, lukehinds commented
Thanks! I wonder if it might be worth mentioning kubewarden , cc @flavio ?

2022-03-10 15:51 UTC, flavio commented
It's all in the open, it can be added.

@msmeissn: can you take care of that as part of this PR or do you want me to follow up once this gets merged?

2022-03-10 16:16 UTC, flavio requested changes
Thanks @msmeissn for adding kubewarden to the list.

2022-03-10 16:16 UTC, flavio commented on SUSE/README.md
>  - [SUSE](https://www.suse.com) is implementing SigStore methods in its Container and Product deliveries.
nitpicking, using the same naming conventions adopted by the sigstore project:

```suggestion
- [SUSE](https://www.suse.com) is implementing sigstore methods in its Container and Product deliveries.
```

2022-03-10 16:16 UTC, flavio commented on SUSE/README.md
>  - The [SUSE Container Registry](https://registry.suse.com/) is now also signing the SUSE containers using "cosign" (additionaly to Notary and Atomic methods) and also uploading signatures to the Linu
nitpicking, using the same naming conventions adopted by the sigstore project. Plus addressing a small typo:

```suggestion
- The [SUSE Container Registry](https://registry.suse.com/) is now also signing the SUSE containers using Cosign (additionally to Notary and Atomic methods) and also uploading signatures to the Linux Foundation Transparency Rekor log.
```

2022-03-10 16:17 UTC, flavio commented
@msmeissn can you also comply with the DCO check please? If that's a trouble I can submit the commit with you as a co-author

2022-03-10 16:40 UTC, lukehinds commented
> @msmeissn can you also comply with the DCO check please? If that's a trouble I can submit the commit with you as a co-author

I can toggle that on as admin, I just need you to say you agree with the DCO

https://wiki.linuxfoundation.org/dco

2022-03-11 09:13 UTC, msmeissn commented
i rebased the commits into 1 with signed-off

I agree to the DCO.

2022-03-11 09:40 UTC, merged